### ISSUE TITLE
Change name to egglog

### ISSUE THREAD

**Issue by saulshanabrook** [metadsl/egglog-python#16]
The upstream repo is [now called `egglog`](https://github.com/egraphs-good/egglog/commit/9484242f025f6c2adb6f29d75a45dd77b0eaad57) instead of `egg-smol`.

We should:

```[tasklist]
### Tasks
- [x] Change the repo name to `egglog-python`
- [x] Change the package name `egglog`
- [x] Update all references in the docs
- [ ] Publish a new version of the package
- [x] Add a citation to the paper in the docs.
- [ ] https://github.com/metadsl/egglog-python/issues/18
```
